services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - 4001:4173
    depends_on:
      - backend
    networks:
      - app-network


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge